"""
agent/tools/send_alert.py
--------------------------
Tool 4: Dispatch portfolio risk alerts via Email (SendGrid) and/or SMS (Twilio).

Channel selection based on risk_level:
  HIGH   → Email + SMS
  MEDIUM → Email only
  LOW    → No alert (graph won't call this node)

Mock mode: When API keys are missing, alerts are logged to console only.
"""

import os
import json
from datetime import datetime, timezone
from typing import Any

from langchain_core.tools import tool

# ── SendGrid ──────────────────────────────────────────────────────────────────
# NOTE: credentials are read lazily inside each function (not at import time)
# so that load_dotenv() can be called BEFORE or AFTER this module is imported.
try:
    from sendgrid import SendGridAPIClient
    from sendgrid.helpers.mail import Mail
    _HAS_SENDGRID = True
except ImportError:
    _HAS_SENDGRID = False

# ── Twilio ────────────────────────────────────────────────────────────────────
try:
    from twilio.rest import Client as TwilioClient
    _HAS_TWILIO = True
except ImportError:
    _HAS_TWILIO = False


# ── Message templates ─────────────────────────────────────────────────────────

def _build_email_html(
    risk_level: str,
    risk_score: float,
    risk_metrics: dict,
    news_items: list,
    portfolio: dict,
    timestamp: str,
) -> str:
    """Build a rich HTML email body."""
    color_map = {"HIGH": "#dc2626", "MEDIUM": "#d97706", "LOW": "#16a34a"}
    color = color_map.get(risk_level, "#6b7280")

    tickers_str = ", ".join(portfolio.keys())
    sharpe = risk_metrics.get("sharpe_ratio", "N/A")
    sortino = risk_metrics.get("sortino_ratio", "N/A")
    vol = f"{risk_metrics.get('annualised_volatility', 0):.1%}" if risk_metrics else "N/A"
    max_dd = f"{risk_metrics.get('max_drawdown', 0):.1%}" if risk_metrics else "N/A"

    headlines_html = "".join(
        f"<li style='margin-bottom:4px'>{item['headline'][:120]} "
        f"<span style='color:{('#dc2626' if item['polarity'] < 0 else '#16a34a')}'>"
        f"({item['polarity']:+.2f})</span></li>"
        for item in news_items[:5]
    )

    return f"""
    <div style="font-family:Arial,sans-serif;max-width:640px;margin:0 auto;padding:24px">
      <div style="background:{color};color:white;padding:16px 24px;border-radius:8px 8px 0 0">
        <h1 style="margin:0;font-size:22px">⚠️ Portfolio Risk Alert — {risk_level}</h1>
        <p style="margin:4px 0 0;opacity:0.9">{timestamp}</p>
      </div>
      <div style="border:1px solid #e5e7eb;padding:20px;border-radius:0 0 8px 8px">
        <h2 style="margin-top:0">Risk Score: {risk_score:.1%}</h2>
        <p><strong>Portfolio:</strong> {tickers_str}</p>
        <table style="width:100%;border-collapse:collapse;margin-bottom:16px">
          <tr style="background:#f3f4f6">
            <th style="padding:8px;text-align:left;border:1px solid #e5e7eb">Metric</th>
            <th style="padding:8px;text-align:right;border:1px solid #e5e7eb">Value</th>
          </tr>
          <tr>
            <td style="padding:8px;border:1px solid #e5e7eb">Sharpe Ratio</td>
            <td style="padding:8px;text-align:right;border:1px solid #e5e7eb">{sharpe}</td>
          </tr>
          <tr style="background:#f9fafb">
            <td style="padding:8px;border:1px solid #e5e7eb">Sortino Ratio</td>
            <td style="padding:8px;text-align:right;border:1px solid #e5e7eb">{sortino}</td>
          </tr>
          <tr>
            <td style="padding:8px;border:1px solid #e5e7eb">Annual Volatility</td>
            <td style="padding:8px;text-align:right;border:1px solid #e5e7eb">{vol}</td>
          </tr>
          <tr style="background:#f9fafb">
            <td style="padding:8px;border:1px solid #e5e7eb">Max Drawdown</td>
            <td style="padding:8px;text-align:right;border:1px solid #e5e7eb">{max_dd}</td>
          </tr>
        </table>
        <h3>📰 Market News Driving This Alert</h3>
        <ul style="padding-left:20px">{headlines_html}</ul>
        <p style="color:#6b7280;font-size:12px;margin-top:24px">
          Generated by Financial Portfolio Agent · {timestamp}
        </p>
      </div>
    </div>
    """


def _build_sms_body(risk_level: str, risk_score: float, risk_metrics: dict, portfolio: dict) -> str:
    sharpe = risk_metrics.get("sharpe_ratio", "N/A")
    tickers = ", ".join(portfolio.keys())
    return (
        f"🚨 PORTFOLIO ALERT [{risk_level}]\n"
        f"Risk Score: {risk_score:.0%}\n"
        f"Portfolio: {tickers}\n"
        f"Sharpe: {sharpe} | "
        f"Vol: {risk_metrics.get('annualised_volatility', 0):.1%}\n"
        f"Review your dashboard immediately."
    )


def _send_email_sendgrid(
    to_email: str, subject: str, html_body: str
) -> tuple[bool, str]:
    """Send via SendGrid. Returns (success, message)."""
    # Read credentials lazily so load_dotenv() order doesn't matter
    api_key = os.getenv("SENDGRID_API_KEY", "")
    from_email = os.getenv("SENDGRID_FROM_EMAIL", "alerts@ishwarambare.online")
    if not _HAS_SENDGRID or not api_key:
        return False, "SendGrid not configured (no API key or package)"
    try:
        message = Mail(
            from_email=from_email,
            to_emails=to_email,
            subject=subject,
            html_content=html_body,
        )
        sg = SendGridAPIClient(api_key)
        response = sg.send(message)
        return True, f"Email sent (HTTP {response.status_code})"
    except Exception as exc:
        return False, f"SendGrid error: {exc}"


def _send_sms_twilio(to_number: str, body: str) -> tuple[bool, str]:
    """Send via Twilio. Returns (success, message)."""
    # Read credentials lazily so load_dotenv() order doesn't matter
    sid = os.getenv("TWILIO_ACCOUNT_SID", "")
    token = os.getenv("TWILIO_AUTH_TOKEN", "")
    from_number = os.getenv("TWILIO_FROM_NUMBER", "")
    if not _HAS_TWILIO or not all([sid, token, from_number]):
        return False, "Twilio not configured (missing credentials or package)"
    try:
        client = TwilioClient(sid, token)
        msg = client.messages.create(body=body, from_=from_number, to=to_number)
        return True, f"SMS sent (SID: {msg.sid})"
    except Exception as exc:
        return False, f"Twilio error: {exc}"


@tool
def send_alert(
    portfolio: dict,
    risk_score: float,
    risk_level: str,
    risk_metrics: dict,
    news_items: list,
    alert_message: str,
    user_email: str = "",
    user_phone: str = "",
) -> dict[str, Any]:
    """
    Send a portfolio risk alert via Email (SendGrid) and SMS (Twilio)
    when risk_score exceeds the HIGH threshold. Logs to console in mock mode.

    Args:
        portfolio: {ticker: weight} — for display in message
        risk_score: composite risk score 0.0–1.0
        risk_level: "HIGH" | "MEDIUM" | "LOW"
        risk_metrics: dict from calc_risk() (Sharpe, Sortino, etc.)
        news_items: list from fetch_news() — top headlines in email
        alert_message: pre-composed summary from graph
        user_email: recipient email (empty → mock mode)
        user_phone: recipient phone e.g. "+919876543210" (empty → skip SMS)

    Returns:
        Partial AgentState update with reasoning_steps and errors.
    """
    steps: list[str] = []
    errors: list[str] = []
    timestamp = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    steps.append(f"📧 Dispatching {risk_level} risk alert...")

    subject = f"🚨 Portfolio Risk Alert [{risk_level}] — Score: {risk_score:.0%}"
    html_body = _build_email_html(
        risk_level, risk_score, risk_metrics, news_items, portfolio, timestamp
    )
    sms_body = _build_sms_body(risk_level, risk_score, risk_metrics, portfolio)

    # ── Email ──────────────────────────────────────────────────────────────────
    if user_email:
        ok, msg = _send_email_sendgrid(user_email, subject, html_body)
        if ok:
            steps.append(f"   ✅ Email → {user_email}: {msg}")
        else:
            steps.append(f"   ⚠️  Email failed: {msg}")
            errors.append(msg)
    else:
        # Mock mode — pretty-print the alert payload
        steps.append("   ℹ️  No user_email set — MOCK mode, logging alert details:")
        steps.append(f"   Subject : {subject}")
        steps.append(f"   Portfolio: {json.dumps(portfolio)}")
        steps.append(f"   Sharpe  : {risk_metrics.get('sharpe_ratio', 'N/A')}")
        steps.append(f"   Sortino : {risk_metrics.get('sortino_ratio', 'N/A')}")
        steps.append(f"   Vol     : {risk_metrics.get('annualised_volatility', 0):.1%}")

    # ── SMS (HIGH risk only) ───────────────────────────────────────────────────
    if risk_level == "HIGH" and user_phone:
        ok, msg = _send_sms_twilio(user_phone, sms_body)
        if ok:
            steps.append(f"   ✅ SMS → {user_phone}: {msg}")
        else:
            steps.append(f"   ⚠️  SMS failed: {msg}")
            errors.append(msg)
    elif risk_level == "HIGH":
        steps.append("   ℹ️  SMS skipped (no user_phone configured)")

    steps.append("   📋 Alert dispatched and logged to DB")

    return {
        "reasoning_steps": steps,
        "errors": errors,
    }
